[package]
name = "simple_pdf_merger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
rfd = "0.9.1"
lopdf = "0.27.0"
rayon = "1.5.3"
egui-toast = "0.3.0"
strsim = "0.10.0"
